/*
 * Files generated by SmartTools.Net Codeless
 * $GenDate$
 *
 */

using $Rootnamespace$.Data;
using $Rootnamespace$.Models;
using $Rootnamespace$.Services;
using Longnows.Saas.Framework.Mvc.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace $Rootnamespace$.Controllers
{
    [Authorize]
    [Area("$area$")]
    public class $ModelName$Controller : SimpleCrudController<$ModelName$Service, $ModelName$, $ModelName$SearchDto>
    {
        #region initialize
        public $ModelName$Controller($ModelName$Service service)
            : base(service)
        {

        }
        #endregion
    }
}
