/*
 * Files generated by SmartTools.Net Codeless
 * $GenDate$
 *
 */

using $Rootnamespace$.Data;
using $Rootnamespace$.Models;
using Longnows.Saas.Framework.Common.Entity;
using Longnows.Saas.Framework.Common.Attributes;
using Longnows.Saas.Framework.DB;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;

namespace $Rootnamespace$.Services
{
    [DI]
    public class $ModelName$Service: SimpleCrudService<$ModelName$,$ModelName$SearchDto>
    {

        #region initialize
        $sqls$
        #endregion

    }
}
